[package]
name = "lowmemmedian"
version = "0.1.0"
authors = ["Evert Rol <evert.rol@gmail.com>"]

[dependencies]
time = "0.1"
rayon = "0.9"
log = "0.4"
env_logger = "0.5.3"

[lib]
name = "lowmemmedian"
path = "src/lib.rs"


[[bin]]
name = "stats"
path = "src/bin/stats.rs"
