[package]
name = "lowmemmedian"
version = "0.1.0"
authors = ["Evert Rol <evert.rol@gmail.com>"]
edition = "2024"

[dependencies]
log = "0.4.26"
env_logger = "0.11.7"

[lib]
name = "lowmemmedian"
path = "src/lib.rs"


[[bin]]
name = "stats"
path = "src/bin/stats.rs"
